server:
  port: 10010
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: p2p-Service
        uri: lb://p2p-service #注册中心调用接口
        order: 0
        predicates:
        - Path=/api/p2p-service/**
        #           - After=2019-11-09T09:54:00.129+08:00[Asia/Shanghai]
        #           - Header=token,[0-5]
        #           - Query=foo,ba.
        #           - Method=GET
        filters:
        - StripPrefix=2
        - AddRequestHeader=X-Request-Foo, Bar #自定义请求头
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/