server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/p2p?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true  #格式化sql
    hibernate:
      ddl-auto: update #自动建表
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    port: 6379
mybatis:
  mapper-locations: classpath*:mapper/*.xml
logging:
  level:
    com.p2p.dao: debug